version: "2"
services:
  cibar-nexus:
    image: sonatype/nexus3
    ports:
      - "21081:8081"
      - "21901:9101"
      - "21903:9103"
      - "21911:9201"
      - "21912:9202"
    volumes:
      - "nexus-data:/nexus-data:z"
    networks:
      devops:

  cibar-sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - cibar-sonarqube-database
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://cibar-sonarqube-database:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - prod_sonarqube_data:/opt/sonarqube/data
      - prod_sonarqube_extensions:/opt/sonarqube/extensions
      - prod_sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "21900:9000"

  cibar-sonarqube-database:
    image: postgres:12
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - cibar-sonarqube-postgresql:/var/lib/postgresql
      - cibar-sonarqube-postgresql-data:/var/lib/postgresql/data

volumes:
  nexus-data:
  prod_sonarqube_data:
    external: true
  prod_sonarqube_extensions:
    external: true
  prod_sonarqube_logs:
    external: true
  cibar-sonarqube-postgresql:
  cibar-sonarqube-postgresql-data:

networks:
  devops:
